import * as c from '@radix-ui/colors'

import type { Recursive, Token } from '../types'

export function colorsToPalette(colors: Record<string, string>, prefix: string, def: string): Record<string, string> {
  const palette: Record<string, string> = {}
  for (const key in colors)
    palette[key.substring(prefix.length)] = colors[key]!
  palette.DEFAULT = def
  return palette
}

export const colors: Recursive<Token<string>> = {
  // gray
  gray: colorsToPalette(c.gray, 'gray', c.gray.gray9),
  grayDark: colorsToPalette(c.grayDark, 'gray', c.grayDark.gray9),
  grayA: colorsToPalette(c.grayA, 'grayA', c.grayA.grayA9),
  grayDarkA: colorsToPalette(c.grayDarkA, 'grayA', c.grayDarkA.grayA9),
  mauve: colorsToPalette(c.mauve, 'mauve', c.mauve.mauve9),
  mauveDark: colorsToPalette(c.mauveDark, 'mauve', c.mauveDark.mauve9),
  mauveA: colorsToPalette(c.mauveA, 'mauveA', c.mauveA.mauveA9),
  mauveDarkA: colorsToPalette(c.mauveDarkA, 'mauveA', c.mauveDarkA.mauveA9),
  slate: colorsToPalette(c.slate, 'slate', c.slate.slate9),
  slateDark: colorsToPalette(c.slateDark, 'slate', c.slateDark.slate9),
  slateA: colorsToPalette(c.slateA, 'slateA', c.slateA.slateA9),
  slateDarkA: colorsToPalette(c.slateDarkA, 'slateA', c.slateDarkA.slateA9),
  sage: colorsToPalette(c.sage, 'sage', c.sage.sage9),
  sageDark: colorsToPalette(c.sageDark, 'sage', c.sageDark.sage9),
  sageA: colorsToPalette(c.sageA, 'sageA', c.sageA.sageA9),
  sageDarkA: colorsToPalette(c.sageDarkA, 'sageA', c.sageDarkA.sageA9),
  olive: colorsToPalette(c.olive, 'olive', c.olive.olive9),
  oliveDark: colorsToPalette(c.oliveDark, 'olive', c.oliveDark.olive9),
  oliveA: colorsToPalette(c.oliveA, 'oliveA', c.oliveA.oliveA9),
  oliveDarkA: colorsToPalette(c.oliveDarkA, 'oliveA', c.oliveDarkA.oliveA9),
  sand: colorsToPalette(c.sand, 'sand', c.sand.sand9),
  sandDark: colorsToPalette(c.sandDark, 'sand', c.sandDark.sand9),
  sandA: colorsToPalette(c.sandA, 'sandA', c.sandA.sandA9),
  sandDarkA: colorsToPalette(c.sandDarkA, 'sandA', c.sandDarkA.sandA9),
  // red
  tomato: colorsToPalette(c.tomato, 'tomato', c.tomato.tomato9),
  tomatoDark: colorsToPalette(c.tomatoDark, 'tomato', c.tomatoDark.tomato9),
  tomatoA: colorsToPalette(c.tomatoA, 'tomatoA', c.tomatoA.tomatoA9),
  tomatoDarkA: colorsToPalette(c.tomatoDarkA, 'tomatoA', c.tomatoDarkA.tomatoA9),
  red: colorsToPalette(c.red, 'red', c.red.red9),
  redDark: colorsToPalette(c.redDark, 'red', c.redDark.red9),
  redA: colorsToPalette(c.redA, 'redA', c.redA.redA9),
  redDarkA: colorsToPalette(c.redDarkA, 'redA', c.redDarkA.redA9),
  ruby: colorsToPalette(c.ruby, 'ruby', c.ruby.ruby9),
  rubyDark: colorsToPalette(c.rubyDark, 'ruby', c.rubyDark.ruby9),
  rubyA: colorsToPalette(c.rubyA, 'rubyA', c.rubyA.rubyA9),
  rubyDarkA: colorsToPalette(c.rubyDarkA, 'rubyA', c.rubyDarkA.rubyA9),
  // pink
  crimson: colorsToPalette(c.crimson, 'crimson', c.crimson.crimson9),
  crimsonDark: colorsToPalette(c.crimsonDark, 'crimson', c.crimsonDark.crimson9),
  crimsonA: colorsToPalette(c.crimsonA, 'crimsonA', c.crimsonA.crimsonA9),
  crimsonDarkA: colorsToPalette(c.crimsonDarkA, 'crimsonA', c.crimsonDarkA.crimsonA9),
  pink: colorsToPalette(c.pink, 'pink', c.pink.pink9),
  pinkDark: colorsToPalette(c.pinkDark, 'pink', c.pinkDark.pink9),
  pinkA: colorsToPalette(c.pinkA, 'pinkA', c.pinkA.pinkA9),
  pinkDarkA: colorsToPalette(c.pinkDarkA, 'pinkA', c.pinkDarkA.pinkA9),
  // purple:
  plum: colorsToPalette(c.plum, 'plum', c.plum.plum9),
  plumDark: colorsToPalette(c.plumDark, 'plum', c.plumDark.plum9),
  plumA: colorsToPalette(c.plumA, 'plumA', c.plumA.plumA9),
  plumDarkA: colorsToPalette(c.plumDarkA, 'plumA', c.plumDarkA.plumA9),
  purple: colorsToPalette(c.purple, 'purple', c.purple.purple9),
  purpleDark: colorsToPalette(c.purpleDark, 'purple', c.purpleDark.purple9),
  purpleA: colorsToPalette(c.purpleA, 'purpleA', c.purpleA.purpleA9),
  purpleDarkA: colorsToPalette(c.purpleDarkA, 'purpleA', c.purpleDarkA.purpleA9),
  violet: colorsToPalette(c.violet, 'violet', c.violet.violet9),
  violetDark: colorsToPalette(c.violetDark, 'violet', c.violetDark.violet9),
  violetA: colorsToPalette(c.violetA, 'violetA', c.violetA.violetA9),
  violetDarkA: colorsToPalette(c.violetDarkA, 'violetA', c.violetDarkA.violetA9),
  iris: colorsToPalette(c.iris, 'iris', c.iris.iris9),
  irisDark: colorsToPalette(c.irisDark, 'iris', c.irisDark.iris9),
  irisA: colorsToPalette(c.irisA, 'irisA', c.irisA.irisA9),
  irisDarkA: colorsToPalette(c.irisDarkA, 'irisA', c.irisDarkA.irisA9),
  // blue
  indigo: colorsToPalette(c.indigo, 'indigo', c.indigo.indigo9),
  indigoDark: colorsToPalette(c.indigoDark, 'indigo', c.indigoDark.indigo9),
  indigoA: colorsToPalette(c.indigoA, 'indigoA', c.indigoA.indigoA9),
  indigoDarkA: colorsToPalette(c.indigoDarkA, 'indigoA', c.indigoDarkA.indigoA9),
  blue: colorsToPalette(c.blue, 'blue', c.blue.blue9),
  blueDark: colorsToPalette(c.blueDark, 'blue', c.blueDark.blue9),
  blueA: colorsToPalette(c.blueA, 'blueA', c.blueA.blueA9),
  blueDarkA: colorsToPalette(c.blueDarkA, 'blueA', c.blueDarkA.blueA9),
  cyan: colorsToPalette(c.cyan, 'cyan', c.cyan.cyan9),
  cyanDark: colorsToPalette(c.cyanDark, 'cyan', c.cyanDark.cyan9),
  cyanA: colorsToPalette(c.cyanA, 'cyanA', c.cyanA.cyanA9),
  cyanDarkA: colorsToPalette(c.cyanDarkA, 'cyanA', c.cyanDarkA.cyanA9),
  // green
  teal: colorsToPalette(c.teal, 'teal', c.teal.teal9),
  tealDark: colorsToPalette(c.tealDark, 'teal', c.tealDark.teal9),
  tealA: colorsToPalette(c.tealA, 'tealA', c.tealA.tealA9),
  tealDarkA: colorsToPalette(c.tealDarkA, 'tealA', c.tealDarkA.tealA9),
  jade: colorsToPalette(c.jade, 'jade', c.jade.jade9),
  jadeDark: colorsToPalette(c.jadeDark, 'jade', c.jadeDark.jade9),
  jadeA: colorsToPalette(c.jadeA, 'jadeA', c.jadeA.jadeA9),
  jadeDarkA: colorsToPalette(c.jadeDarkA, 'jadeA', c.jadeDarkA.jadeA9),
  green: colorsToPalette(c.green, 'green', c.green.green9),
  greenDark: colorsToPalette(c.greenDark, 'green', c.greenDark.green9),
  greenA: colorsToPalette(c.greenA, 'greenA', c.greenA.greenA9),
  greenDarkA: colorsToPalette(c.greenDarkA, 'greenA', c.greenDarkA.greenA9),
  grass: colorsToPalette(c.grass, 'grass', c.grass.grass9),
  grassDark: colorsToPalette(c.grassDark, 'grass', c.grassDark.grass9),
  grassA: colorsToPalette(c.grassA, 'grassA', c.grassA.grassA9),
  grassDarkA: colorsToPalette(c.grassDarkA, 'grassA', c.grassDarkA.grassA9),
  // bronze
  bronze: colorsToPalette(c.bronze, 'bronze', c.bronze.bronze9),
  bronzeDark: colorsToPalette(c.bronzeDark, 'bronze', c.bronzeDark.bronze9),
  bronzeA: colorsToPalette(c.bronzeA, 'bronzeA', c.bronzeA.bronzeA9),
  bronzeDarkA: colorsToPalette(c.bronzeDarkA, 'bronzeA', c.bronzeDarkA.bronzeA9),
  gold: colorsToPalette(c.gold, 'gold', c.gold.gold9),
  goldDark: colorsToPalette(c.goldDark, 'gold', c.goldDark.gold9),
  goldA: colorsToPalette(c.goldA, 'goldA', c.goldA.goldA9),
  goldDarkA: colorsToPalette(c.goldDarkA, 'goldA', c.goldDarkA.goldA9),
  brown: colorsToPalette(c.brown, 'brown', c.brown.brown9),
  brownDark: colorsToPalette(c.brownDark, 'brown', c.brownDark.brown9),
  brownA: colorsToPalette(c.brownA, 'brownA', c.brownA.brownA9),
  brownDarkA: colorsToPalette(c.brownDarkA, 'brownA', c.brownDarkA.brownA9),
  // orange
  orange: colorsToPalette(c.orange, 'orange', c.orange.orange9),
  orangeDark: colorsToPalette(c.orangeDark, 'orange', c.orangeDark.orange9),
  orangeA: colorsToPalette(c.orangeA, 'orangeA', c.orangeA.orangeA9),
  orangeDarkA: colorsToPalette(c.orangeDarkA, 'orangeA', c.orangeDarkA.orangeA9),
  // yellow
  amber: colorsToPalette(c.amber, 'amber', c.amber.amber9),
  amberDark: colorsToPalette(c.amberDark, 'amber', c.amberDark.amber9),
  amberA: colorsToPalette(c.amberA, 'amberA', c.amberA.amberA9),
  amberDarkA: colorsToPalette(c.amberDarkA, 'amberA', c.amberDarkA.amberA9),
  yellow: colorsToPalette(c.yellow, 'yellow', c.yellow.yellow9),
  yellowDark: colorsToPalette(c.yellowDark, 'yellow', c.yellowDark.yellow9),
  yellowA: colorsToPalette(c.yellowA, 'yellowA', c.yellowA.yellowA9),
  yellowDarkA: colorsToPalette(c.yellowDarkA, 'yellowA', c.yellowDarkA.yellowA9),
  // light
  lime: colorsToPalette(c.lime, 'lime', c.lime.lime9),
  limeDark: colorsToPalette(c.limeDark, 'lime', c.limeDark.lime9),
  limeA: colorsToPalette(c.limeA, 'limeA', c.limeA.limeA9),
  limeDarkA: colorsToPalette(c.limeDarkA, 'limeA', c.limeDarkA.limeA9),
  mint: colorsToPalette(c.mint, 'mint', c.mint.mint9),
  mintDark: colorsToPalette(c.mintDark, 'mint', c.mintDark.mint9),
  mintA: colorsToPalette(c.mintA, 'mintA', c.mintA.mintA9),
  mintDarkA: colorsToPalette(c.mintDarkA, 'mintA', c.mintDarkA.mintA9),
  sky: colorsToPalette(c.sky, 'sky', c.sky.sky9),
  skyDark: colorsToPalette(c.skyDark, 'sky', c.skyDark.sky9),
  skyA: colorsToPalette(c.skyA, 'skyA', c.skyA.skyA9),
  skyDarkA: colorsToPalette(c.skyDarkA, 'skyA', c.skyDarkA.skyA9),
  // black alpha
  blackA: colorsToPalette(c.blackA, 'blackA', c.blackA.blackA9),
  // white alpha
  whiteA: colorsToPalette(c.whiteA, 'whiteA', c.whiteA.whiteA9),
}

export const colorsP3: Recursive<Token<string>> = {
  // gray
  gray: colorsToPalette(c.grayP3, 'gray', c.grayP3.gray9),
  grayDark: colorsToPalette(c.grayDarkP3, 'gray', c.grayDarkP3.gray9),
  grayA: colorsToPalette(c.grayP3A, 'grayA', c.grayP3A.grayA9),
  grayDarkA: colorsToPalette(c.grayDarkP3A, 'grayA', c.grayDarkP3A.grayA9),
  mauve: colorsToPalette(c.mauveP3, 'mauve', c.mauveP3.mauve9),
  mauveDark: colorsToPalette(c.mauveDarkP3, 'mauve', c.mauveDarkP3.mauve9),
  mauveA: colorsToPalette(c.mauveP3A, 'mauveA', c.mauveP3A.mauveA9),
  mauveDarkA: colorsToPalette(c.mauveDarkP3A, 'mauveA', c.mauveDarkP3A.mauveA9),
  slate: colorsToPalette(c.slateP3, 'slate', c.slateP3.slate9),
  slateDark: colorsToPalette(c.slateDarkP3, 'slate', c.slateDarkP3.slate9),
  slateA: colorsToPalette(c.slateP3A, 'slateA', c.slateP3A.slateA9),
  slateDarkA: colorsToPalette(c.slateDarkP3A, 'slateA', c.slateDarkP3A.slateA9),
  sage: colorsToPalette(c.sageP3, 'sage', c.sageP3.sage9),
  sageDark: colorsToPalette(c.sageDarkP3, 'sage', c.sageDarkP3.sage9),
  sageA: colorsToPalette(c.sageP3A, 'sageA', c.sageP3A.sageA9),
  sageDarkA: colorsToPalette(c.sageDarkP3A, 'sageA', c.sageDarkP3A.sageA9),
  olive: colorsToPalette(c.oliveP3, 'olive', c.oliveP3.olive9),
  oliveDark: colorsToPalette(c.oliveDarkP3, 'olive', c.oliveDarkP3.olive9),
  oliveA: colorsToPalette(c.oliveP3A, 'oliveA', c.oliveP3A.oliveA9),
  oliveDarkA: colorsToPalette(c.oliveDarkP3A, 'oliveA', c.oliveDarkP3A.oliveA9),
  sand: colorsToPalette(c.sandP3, 'sand', c.sandP3.sand9),
  sandDark: colorsToPalette(c.sandDarkP3, 'sand', c.sandDarkP3.sand9),
  sandA: colorsToPalette(c.sandP3A, 'sandA', c.sandP3A.sandA9),
  sandDarkA: colorsToPalette(c.sandDarkP3A, 'sandA', c.sandDarkP3A.sandA9),
  // red
  tomato: colorsToPalette(c.tomatoP3, 'tomato', c.tomatoP3.tomato9),
  tomatoDark: colorsToPalette(c.tomatoDarkP3, 'tomato', c.tomatoDarkP3.tomato9),
  tomatoA: colorsToPalette(c.tomatoP3A, 'tomatoA', c.tomatoP3A.tomatoA9),
  tomatoDarkA: colorsToPalette(c.tomatoDarkP3A, 'tomatoA', c.tomatoDarkP3A.tomatoA9),
  red: colorsToPalette(c.redP3, 'red', c.redP3.red9),
  redDark: colorsToPalette(c.redDarkP3, 'red', c.redDarkP3.red9),
  redA: colorsToPalette(c.redP3A, 'redA', c.redP3A.redA9),
  redDarkA: colorsToPalette(c.redDarkP3A, 'redA', c.redDarkP3A.redA9),
  ruby: colorsToPalette(c.rubyP3, 'ruby', c.rubyP3.ruby9),
  rubyDark: colorsToPalette(c.rubyDarkP3, 'ruby', c.rubyDarkP3.ruby9),
  rubyA: colorsToPalette(c.rubyP3A, 'rubyA', c.rubyP3A.rubyA9),
  rubyDarkA: colorsToPalette(c.rubyDarkP3A, 'rubyA', c.rubyDarkP3A.rubyA9),
  // pink
  crimson: colorsToPalette(c.crimsonP3, 'crimson', c.crimsonP3.crimson9),
  crimsonDark: colorsToPalette(c.crimsonDarkP3, 'crimson', c.crimsonDarkP3.crimson9),
  crimsonA: colorsToPalette(c.crimsonP3A, 'crimsonA', c.crimsonP3A.crimsonA9),
  crimsonDarkA: colorsToPalette(c.crimsonDarkP3A, 'crimsonA', c.crimsonDarkP3A.crimsonA9),
  pink: colorsToPalette(c.pinkP3, 'pink', c.pinkP3.pink9),
  pinkDark: colorsToPalette(c.pinkDarkP3, 'pink', c.pinkDarkP3.pink9),
  pinkA: colorsToPalette(c.pinkP3A, 'pinkA', c.pinkP3A.pinkA9),
  pinkDarkA: colorsToPalette(c.pinkDarkP3A, 'pinkA', c.pinkDarkP3A.pinkA9),
  // purple:
  plum: colorsToPalette(c.plumP3, 'plum', c.plumP3.plum9),
  plumDark: colorsToPalette(c.plumDarkP3, 'plum', c.plumDarkP3.plum9),
  plumA: colorsToPalette(c.plumP3A, 'plumA', c.plumP3A.plumA9),
  plumDarkA: colorsToPalette(c.plumDarkP3A, 'plumA', c.plumDarkP3A.plumA9),
  purple: colorsToPalette(c.purpleP3, 'purple', c.purpleP3.purple9),
  purpleDark: colorsToPalette(c.purpleDarkP3, 'purple', c.purpleDarkP3.purple9),
  purpleA: colorsToPalette(c.purpleP3A, 'purpleA', c.purpleP3A.purpleA9),
  purpleDarkA: colorsToPalette(c.purpleDarkP3A, 'purpleA', c.purpleDarkP3A.purpleA9),
  violet: colorsToPalette(c.violetP3, 'violet', c.violetP3.violet9),
  violetDark: colorsToPalette(c.violetDarkP3, 'violet', c.violetDarkP3.violet9),
  violetA: colorsToPalette(c.violetP3A, 'violetA', c.violetP3A.violetA9),
  violetDarkA: colorsToPalette(c.violetDarkP3A, 'violetA', c.violetDarkP3A.violetA9),
  iris: colorsToPalette(c.irisP3, 'iris', c.irisP3.iris9),
  irisDark: colorsToPalette(c.irisDarkP3, 'iris', c.irisDarkP3.iris9),
  irisA: colorsToPalette(c.irisP3A, 'irisA', c.irisP3A.irisA9),
  irisDarkA: colorsToPalette(c.irisDarkP3A, 'irisA', c.irisDarkP3A.irisA9),
  // blue
  indigo: colorsToPalette(c.indigoP3, 'indigo', c.indigoP3.indigo9),
  indigoDark: colorsToPalette(c.indigoDarkP3, 'indigo', c.indigoDarkP3.indigo9),
  indigoA: colorsToPalette(c.indigoP3A, 'indigoA', c.indigoP3A.indigoA9),
  indigoDarkA: colorsToPalette(c.indigoDarkP3A, 'indigoA', c.indigoDarkP3A.indigoA9),
  blue: colorsToPalette(c.blueP3, 'blue', c.blueP3.blue9),
  blueDark: colorsToPalette(c.blueDarkP3, 'blue', c.blueDarkP3.blue9),
  blueA: colorsToPalette(c.blueP3A, 'blueA', c.blueP3A.blueA9),
  blueDarkA: colorsToPalette(c.blueDarkP3A, 'blueA', c.blueDarkP3A.blueA9),
  cyan: colorsToPalette(c.cyanP3, 'cyan', c.cyanP3.cyan9),
  cyanDark: colorsToPalette(c.cyanDarkP3, 'cyan', c.cyanDarkP3.cyan9),
  cyanA: colorsToPalette(c.cyanP3A, 'cyanA', c.cyanP3A.cyanA9),
  cyanDarkA: colorsToPalette(c.cyanDarkP3A, 'cyanA', c.cyanDarkP3A.cyanA9),
  // green
  teal: colorsToPalette(c.tealP3, 'teal', c.tealP3.teal9),
  tealDark: colorsToPalette(c.tealDarkP3, 'teal', c.tealDarkP3.teal9),
  tealA: colorsToPalette(c.tealP3A, 'tealA', c.tealP3A.tealA9),
  tealDarkA: colorsToPalette(c.tealDarkP3A, 'tealA', c.tealDarkP3A.tealA9),
  jade: colorsToPalette(c.jadeP3, 'jade', c.jadeP3.jade9),
  jadeDark: colorsToPalette(c.jadeDarkP3, 'jade', c.jadeDarkP3.jade9),
  jadeA: colorsToPalette(c.jadeP3A, 'jadeA', c.jadeP3A.jadeA9),
  jadeDarkA: colorsToPalette(c.jadeDarkP3A, 'jadeA', c.jadeDarkP3A.jadeA9),
  green: colorsToPalette(c.greenP3, 'green', c.greenP3.green9),
  greenDark: colorsToPalette(c.greenDarkP3, 'green', c.greenDarkP3.green9),
  greenA: colorsToPalette(c.greenP3A, 'greenA', c.greenP3A.greenA9),
  greenDarkA: colorsToPalette(c.greenDarkP3A, 'greenA', c.greenDarkP3A.greenA9),
  grass: colorsToPalette(c.grassP3, 'grass', c.grassP3.grass9),
  grassDark: colorsToPalette(c.grassDarkP3, 'grass', c.grassDarkP3.grass9),
  grassA: colorsToPalette(c.grassP3A, 'grassA', c.grassP3A.grassA9),
  grassDarkA: colorsToPalette(c.grassDarkP3A, 'grassA', c.grassDarkP3A.grassA9),
  // bronze
  bronze: colorsToPalette(c.bronzeP3, 'bronze', c.bronzeP3.bronze9),
  bronzeDark: colorsToPalette(c.bronzeDarkP3, 'bronze', c.bronzeDarkP3.bronze9),
  bronzeA: colorsToPalette(c.bronzeP3A, 'bronzeA', c.bronzeP3A.bronzeA9),
  bronzeDarkA: colorsToPalette(c.bronzeDarkP3A, 'bronzeA', c.bronzeDarkP3A.bronzeA9),
  gold: colorsToPalette(c.goldP3, 'gold', c.goldP3.gold9),
  goldDark: colorsToPalette(c.goldDarkP3, 'gold', c.goldDarkP3.gold9),
  goldA: colorsToPalette(c.goldP3A, 'goldA', c.goldP3A.goldA9),
  goldDarkA: colorsToPalette(c.goldDarkP3A, 'goldA', c.goldDarkP3A.goldA9),
  brown: colorsToPalette(c.brownP3, 'brown', c.brownP3.brown9),
  brownDark: colorsToPalette(c.brownDarkP3, 'brown', c.brownDarkP3.brown9),
  brownA: colorsToPalette(c.brownP3A, 'brownA', c.brownP3A.brownA9),
  brownDarkA: colorsToPalette(c.brownDarkP3A, 'brownA', c.brownDarkP3A.brownA9),
  // orange
  orange: colorsToPalette(c.orangeP3, 'orange', c.orangeP3.orange9),
  orangeDark: colorsToPalette(c.orangeDarkP3, 'orange', c.orangeDarkP3.orange9),
  orangeA: colorsToPalette(c.orangeP3A, 'orangeA', c.orangeP3A.orangeA9),
  orangeDarkA: colorsToPalette(c.orangeDarkP3A, 'orangeA', c.orangeDarkP3A.orangeA9),
  // yellow
  amber: colorsToPalette(c.amberP3, 'amber', c.amberP3.amber9),
  amberDark: colorsToPalette(c.amberDarkP3, 'amber', c.amberDarkP3.amber9),
  amberA: colorsToPalette(c.amberP3A, 'amberA', c.amberP3A.amberA9),
  amberDarkA: colorsToPalette(c.amberDarkP3A, 'amberA', c.amberDarkP3A.amberA9),
  yellow: colorsToPalette(c.yellowP3, 'yellow', c.yellowP3.yellow9),
  yellowDark: colorsToPalette(c.yellowDarkP3, 'yellow', c.yellowDarkP3.yellow9),
  yellowA: colorsToPalette(c.yellowP3A, 'yellowA', c.yellowP3A.yellowA9),
  yellowDarkA: colorsToPalette(c.yellowDarkP3A, 'yellowA', c.yellowDarkP3A.yellowA9),
  // light
  lime: colorsToPalette(c.limeP3, 'lime', c.limeP3.lime9),
  limeDark: colorsToPalette(c.limeDarkP3, 'lime', c.limeDarkP3.lime9),
  limeA: colorsToPalette(c.limeP3A, 'limeA', c.limeP3A.limeA9),
  limeDarkA: colorsToPalette(c.limeDarkP3A, 'limeA', c.limeDarkP3A.limeA9),
  mint: colorsToPalette(c.mintP3, 'mint', c.mintP3.mint9),
  mintDark: colorsToPalette(c.mintDarkP3, 'mint', c.mintDarkP3.mint9),
  mintA: colorsToPalette(c.mintP3A, 'mintA', c.mintP3A.mintA9),
  mintDarkA: colorsToPalette(c.mintDarkP3A, 'mintA', c.mintDarkP3A.mintA9),
  sky: colorsToPalette(c.skyP3, 'sky', c.skyP3.sky9),
  skyDark: colorsToPalette(c.skyDarkP3, 'sky', c.skyDarkP3.sky9),
  skyA: colorsToPalette(c.skyP3A, 'skyA', c.skyP3A.skyA9),
  skyDarkA: colorsToPalette(c.skyDarkP3A, 'skyA', c.skyDarkP3A.skyA9),
  // black alpha
  blackA: colorsToPalette(c.blackP3A, 'blackA', c.blackP3A.blackA9),
  // white alpha
  whiteA: colorsToPalette(c.whiteP3A, 'whiteA', c.whiteP3A.whiteA9),
}
